
import { PrimeMinister } from '../types';
import { ROUNDS_PER_GAME } from '../constants';
import andyBurnhamPortrait from '../src/assets/images/andy_burnham_portrait_1784578546880.jpg';

// This file can be updated via the in-game admin panel.
export const allPrimeMinisters: PrimeMinister[] = [
  { "id": 1, "name": "Robert Walpole", "party": "Whig", "termStart": 1721, "termEnd": 1742, "context": "Often regarded as the first de facto Prime Minister, he established political stability and pursued a policy of peace.", "contextFr": "Souvent considéré comme le premier véritable Premier ministre, il a établi la stabilité politique et poursuivi une politique de paix.", "contextJa": "事実上の初代首相と見なされることが多く、政治的安定を確立し、平和政策を追求しました。", "contextEs": "A menudo considerado como el primer Primer Ministro de facto, estableció la estabilidad política y siguió una política de paz.", "contextZh": "通常被认为是第一位事实上的首相，他建立了政治稳定并奉行和平政策。", "contextAr": "يُعتبر غالبًا أول رئيس وزراء فعلي، أسس الاستقرار السياسي واتبع سياسة السلام.", "contextHi": "अक्सर पहले वास्तविक प्रधानमंत्री के रूप में माने जाने वाले, उन्होंने राजनीतिक स्थिरता स्थापित की और शांति की नीति अपनाई।", "imageUrl": "https://i.ibb.co/pB2W65Zc/Robert-Walpole-1st-Earl-of-Orford.webp", "coatOfArmsUrl": "https://i.ibb.co/DZqGvpd/whig2.png" },
  { "id": 2, "name": "William Pitt the Elder", "party": "Whig", "termStart": 1766, "termEnd": 1768, "context": "Known as 'The Great Commoner', he led Britain to victory in the Seven Years' War, expanding its global empire.", "contextFr": "Connu sous le nom de « The Great Commoner », il a mené la Grande-Bretagne à la victoire lors de la guerre de Sept Ans, étendant son empire mondial.", "contextJa": "「大平民」として知られ、七年戦争で英国を勝利に導き、世界帝国を拡大しました。", "contextEs": "Conocido como 'El Gran Plebeyo', llevó a Gran Bretaña a la victoria en la Guerra de los Siete Años, expandiendo su imperio global.", "contextZh": "被称为“伟大的平民”，他带领英国在七年战争中取得胜利，扩大了其全球帝国。", "contextAr": "يُعرف باسم 'العامي العظيم'، قاد بريطانيا إلى النصر في حرب السنوات السبع، ووسع إمبراطوريتها العالمية.", "contextHi": "'द ग्रेट कॉमनर' के रूप में जाने जाने वाले, उन्होंने सात साल के युद्ध में ब्रिटेन को जीत दिलाई, इसके वैश्विक साम्राज्य का विस्तार किया।", "imageUrl": "https://i.ibb.co/Z6MxV7fd/F-William-Pitt-1st-Earl-of-Chatham.webp", "coatOfArmsUrl": "https://i.ibb.co/DZqGvpd/whig2.png" },
  { "id": 3, "name": "Lord North", "party": "Tory", "termStart": 1770, "termEnd": 1782, "context": "His premiership was dominated by the American War of Independence, which ended in defeat for Britain.", "contextFr": "Son mandat a été dominé par la guerre d'Indépendance américaine, qui s'est soldée par une défaite pour la Grande-Bretagne.", "contextJa": "彼の任期はアメリカ独立戦争に支配され、英国の敗北に終わりました。", "contextEs": "Su mandato estuvo dominado por la Guerra de Independencia de los Estados Unidos, que terminó en derrota para Gran Bretaña.", "contextZh": "他的任期被美国独立战争所主导，该战争以英国的失败告终。", "contextAr": "هيمنت حرب الاستقلال الأمريكية على فترة ولايته، والتي انتهت بهزيمة بريطانيا.", "contextHi": "उनका कार्यकाल अमेरिकी स्वतंत्रता संग्राम के प्रभुत्व में था, जो ब्रिटेन के लिए हार में समाप्त हुआ।", "imageUrl": "https://i.ibb.co/0jTzsWby/Frederick-North-2nd-Earl-of-Guilford.webp", "coatOfArmsUrl": "https://i.ibb.co/gFL96Vzk/Tory.png" },
  { "id": 4, "name": "William Pitt the Younger", "party": "Tory", "termStart": 1783, "termEnd": 1801, "context": "Became Prime Minister at age 24. He guided the country through the French Revolutionary and Napoleonic Wars.", "contextFr": "Devenu Premier ministre à 24 ans. Il a guidé le pays à travers les guerres de la Révolution française et napoléoniennes.", "contextJa": "24歳で首相に就任。フランス革命戦争とナポレオン戦争を通じて国を導きました。", "contextEs": "Se convirtió en Primer Ministro a los 24 años. Guió al país a través de las Guerras Revolucionarias Francesas y Napoleónicas.", "contextZh": "24岁成为首相。他带领国家度过了法国大革命和拿破仑战争。", "contextAr": "أصبح رئيسًا للوزراء في سن 24. قاد البلاد خلال الحروب الثورية الفرنسية والنابليونية.", "contextHi": "24 साल की उम्र में प्रधानमंत्री बने। उन्होंने फ्रांसीसी क्रांतिकारी और नेपोलियन युद्धों के माध्यम से देश का मार्गदर्शन किया।", "imageUrl": "https://i.ibb.co/qLybVDMk/Older-Pitt-The-Younger.webp", "coatOfArmsUrl": "https://i.ibb.co/gFL96Vzk/Tory.png" },
  { "id": 5, "name": "Spencer Perceval", "party": "Tory", "termStart": 1809, "termEnd": 1812, "context": "He is the only British Prime Minister to have been assassinated, shot in the lobby of the House of Commons.", "contextFr": "Il est le seul Premier ministre britannique à avoir été assassiné, abattu dans le hall de la Chambre des communes.", "contextJa": "英国の首相で唯一暗殺された人物であり、庶民院のロビーで撃たれました。", "contextEs": "Es el único Primer Ministro británico que ha sido asesinado, recibiendo un disparo en el vestíbulo de la Cámara de los Comunes.", "contextZh": "他是唯一一位被暗杀的英国首相，在下议院大厅被枪杀。", "contextAr": "هو رئيس الوزراء البريطاني الوحيد الذي تم اغتياله، حيث قُتل بالرصاص في بهو مجلس العموم.", "contextHi": "वह एकमात्र ब्रिटिश प्रधानमंत्री हैं जिनकी हत्या की गई है, उन्हें हाउस ऑफ कॉमन्स की लॉबी में गोली मार दी गई थी।", "imageUrl": "https://i.ibb.co/pv5PNWr0/Spencer-Perceval.webp", "coatOfArmsUrl": "https://i.ibb.co/gFL96Vzk/Tory.png" },
  { "id": 6, "name": "Robert Jenkinson, 2nd Earl of Liverpool", "party": "Tory", "termStart": 1812, "termEnd": 1827, "context": "His long term in office saw victory at the Battle of Waterloo and the controversial Corn Laws.", "contextFr": "Son long mandat a vu la victoire à la bataille de Waterloo et les controversées Corn Laws.", "contextJa": "彼の長期政権は、ワーテルローの戦いでの勝利と物議を醸した穀物法を見届けました。", "contextEs": "Su largo mandato vio la victoria en la Batalla de Waterloo y las controvertidas Leyes de los Cereales.", "contextZh": "他漫长的任期见证了滑铁卢战役的胜利和备受争议的《谷物法》。", "contextAr": "شهدت فترة ولايته الطويلة النصر في معركة واترلو وقوانين الذرة المثيرة للجدل.", "contextHi": "उनके लंबे कार्यकाल में वाटरलू की लड़ाई में जीत और विवादास्पद कॉर्न लॉ देखे गए।", "imageUrl": "https://i.ibb.co/DPSKV62z/Robert-Banks-Jenkinson-2nd-Earl-of-Liverpool.webp", "coatOfArmsUrl": "https://i.ibb.co/gFL96Vzk/Tory.png" },
  { "id": 7, "name": "Arthur Wellesley, 1st Duke of Wellington", "party": "Tory", "termStart": 1828, "termEnd": 1830, "context": "The 'Iron Duke', famous for defeating Napoleon at Waterloo, he passed the Catholic Emancipation Act.", "contextFr": "Le « Duc de fer », célèbre pour avoir vaincu Napoléon à Waterloo, il a fait adopter l'Acte d'émancipation des catholiques.", "contextJa": "「鉄の公爵」としてワーテルローでナポレオンを破ったことで有名であり、カトリック解放法を成立させました。", "contextEs": "El 'Duque de Hierro', famoso por derrotar a Napoleón en Waterloo, aprobó el Acta de Emancipación Católica.", "contextZh": "“铁公爵”，以在滑铁卢击败拿破仑而闻名，他通过了《天主教解放法案》。", "contextAr": "'الدوق الحديدي'، المشهور بهزيمة نابليون في واترلو، أقر قانون التحرر الكاثوليكي.", "contextHi": "'आयरन ड्यूक', वाटरलू में नेपोलियन को हराने के लिए प्रसिद्ध, उन्होंने कैथोलिक मुक्ति अधिनियम पारित किया।", "imageUrl": "https://i.ibb.co/Zz56HDkv/Sir-Arthur-Wellesley-1st-Duke-of-Wellington-1.webp", "coatOfArmsUrl": "https://i.ibb.co/gFL96Vzk/Tory.png" },
  { "id": 8, "name": "Charles Grey, 2nd Earl Grey", "party": "Whig", "termStart": 1830, "termEnd": 1834, "context": "Oversaw the passage of the Great Reform Act of 1832 and the abolition of slavery in the British Empire.", "contextFr": "A supervisé l'adoption du Great Reform Act de 1832 et l'abolition de l'esclavage dans l'Empire britannique.", "contextJa": "1832年の大改革法の成立と大英帝国における奴隷制の廃止を監督しました。", "contextEs": "Supervisó la aprobación de la Gran Ley de Reforma de 1832 y la abolición de la esclavitud en el Imperio Británico.", "contextZh": "监督通过了1832年《大改革法案》以及在大英帝国废除奴隶制。", "contextAr": "أشرف على إقرار قانون الإصلاح العظيم لعام 1832 وإلغاء العبودية في الإمبراطورية البريطانية.", "contextHi": "1832 के महान सुधार अधिनियम के पारित होने और ब्रिटिश साम्राज्य में गुलामी के उन्मूलन की देखरेख की।", "imageUrl": "https://i.ibb.co/PGzgg2k9/Charles-Grey-2nd-Earl-Grey.webp", "coatOfArmsUrl": "https://i.ibb.co/DZqGvpd/whig2.png" },
  { "id": 9, "name": "Robert Peel", "party": "Conservative", "termStart": 1834, "termEnd": 1835, "context": "Created the Metropolitan Police Force (hence 'Bobbies'). His Tamworth Manifesto laid the foundations of the modern Conservative Party.", "contextFr": "A créé la Metropolitan Police Force (d'où les « Bobbies »). Son Manifeste de Tamworth a jeté les bases du Parti conservateur moderne.", "contextJa": "首都警察（ゆえに「ボビー」）を創設。彼のタムワース宣言は現代保守党の基礎を築きました。", "contextEs": "Creó la Policía Metropolitana (de ahí los 'Bobbies'). Su Manifiesto de Tamworth sentó las bases del Partido Conservador moderno.", "contextZh": "创建了伦敦警察厅（因此被称为“Bobbies”）。他的《塔姆沃思宣言》奠定了现代保守党的基础。", "contextAr": "أنشأ قوة شرطة العاصمة (ومن هنا جاء اسم 'بوبيز'). أرسى بيان تامورث الخاص به أسس حزب المحافظين الحديث.", "contextHi": "मेट्रोपॉलिटन पुलिस फोर्स (इसलिए 'बॉबीज़') बनाया। उनके टैमवर्थ मेनिफेस्टो ने आधुनिक कंजर्वेटिव पार्टी की नींव रखी।", "imageUrl": "https://i.ibb.co/GQPMjFv9/Sir-Robert-Peel-2nd-Bt.webp", "coatOfArmsUrl": "https://i.ibb.co/gFL96Vzk/Tory.png" },
  { "id": 10, "name": "Lord Melbourne", "party": "Whig", "termStart": 1835, "termEnd": 1841, "context": "He was a political mentor to the young Queen Victoria upon her accession to the throne in 1837.", "contextFr": "Il a été un mentor politique pour la jeune reine Victoria lors de son accession au trône en 1837.", "contextJa": "1837年に王位に就いた若きヴィクトリア女王の政治的良き助言者でした。", "contextEs": "Fue mentor político de la joven reina Victoria tras su ascenso al trono en 1837.", "contextZh": "在年轻的维多利亚女王1837年登基时，他是她的政治导师。", "contextAr": "كان مرشدًا سياسيًا للملكة الشابة فيكتوريا عند اعتلائها العرش في عام 1837.", "contextHi": "1837 में सिंहासन पर बैठने पर वह युवा रानी विक्टोरिया के राजनीतिक गुरु थे।", "imageUrl": "https://i.ibb.co/PZm6v25t/William-Lamb-2nd-Viscount-Melbourne.webp", "coatOfArmsUrl": "https://i.ibb.co/DZqGvpd/whig2.png" },
  { "id": 11, "name": "Lord Palmerston", "party": "Liberal", "termStart": 1855, "termEnd": 1858, "context": "A dominant figure in foreign policy for many years, his approach became known as 'gunboat diplomacy'.", "contextFr": "Figure dominante de la politique étrangère pendant de nombreuses années, son approche est devenue connue sous le nom de « diplomatie de la canonnière ».", "contextJa": "長年にわたり外交政策の支配的な人物であり、彼のアプローチは「砲艦外交」として知られるようになりました。", "contextEs": "Una figura dominante en la política exterior durante muchos años, su enfoque se conoció como 'diplomacia de cañoneras'.", "contextZh": "多年来在外交政策中占据主导地位，他的方法被称为“炮舰外交”。", "contextAr": "شخصية مهيمنة في السياسة الخارجية لسنوات عديدة، أصبح نهجه يُعرف باسم 'دبلوماسية الزوارق الحربية'.", "contextHi": "कई वर्षों तक विदेश नीति में एक प्रमुख व्यक्ति, उनके दृष्टिकोण को 'गनरबोट कूटनीति' के रूप में जाना जाने लगा।", "imageUrl": "https://i.ibb.co/1fzFh7tb/Henry-John-Temple-3rd-Viscount-Palmerston.webp", "coatOfArmsUrl": "https://i.ibb.co/1YPWCxVK/LibDems.png" },
  { "id": 12, "name": "Benjamin Disraeli", "party": "Conservative", "termStart": 1868, "termEnd": 1868, "context": "A novelist and politician who bought shares in the Suez Canal and had a notable rivalry with Gladstone.", "contextFr": "Romancier et homme politique qui a acheté des parts dans le canal de Suez et a eu une rivalité notable avec Gladstone.", "contextJa": "スエズ運河の株式を購入し、グラッドストンと顕著なライバル関係にあった小説家兼政治家。", "contextEs": "Novelista y político que compró acciones del Canal de Suez y tuvo una notable rivalidad con Gladstone.", "contextZh": "一位小说家和政治家，购买了苏伊士运河的股份，并与格莱斯顿有着著名的竞争关系。", "contextAr": "روائي وسياسي اشترى أسهمًا في قناة السويس وكان له تنافس ملحوظ مع جلادستون.", "contextHi": "एक उपन्यासकार और राजनेता, जिन्होंने स्वेज नहर के शेयर खरीदे और ग्लैडस्टोन के साथ एक उल्लेखनीय प्रतिद्वंद्विता की।", "imageUrl": "https://i.ibb.co/nNNkkhkd/Benjamin-Disraeli-Earl-of-Beaconsfield.webp", "coatOfArmsUrl": "https://i.ibb.co/gFL96Vzk/Tory.png" },
  { "id": 13, "name": "William Gladstone", "party": "Liberal", "termStart": 1868, "termEnd": 1874, "context": "Served as Prime Minister four separate times, championing electoral reform and attempting to solve the 'Irish Question'.", "contextFr": "A été Premier ministre à quatre reprises, défendant la réforme électorale et tentant de résoudre la « question irlandaise ».", "contextJa": "4度首相を務め、選挙制度改革を推進し、「アイルランド問題」の解決を試みました。", "contextEs": "Se desempeñó como Primer Ministro en cuatro ocasiones distintas, defendiendo la reforma electoral e intentando resolver la 'Cuestión Irlandesa'.", "contextZh": "曾四次担任首相，倡导选举改革并试图解决“爱尔兰问题”。", "contextAr": "شغل منصب رئيس الوزراء أربع مرات منفصلة، ودافع عن الإصلاح الانتخابي وحاول حل 'المسألة الأيرلندية'.", "contextHi": "चार अलग-अलग अवसरों पर प्रधानमंत्री के रूप में कार्य किया, चुनावी सुधार का समर्थन किया और 'आयरिश प्रश्न' को हल करने का प्रयास किया।", "imageUrl": "https://i.ibb.co/0RYfk6ZL/William-Ewart-Gladstone.webp", "coatOfArmsUrl": "https://i.ibb.co/1YPWCxVK/LibDems.png" },
  { "id": 14, "name": "Lord Salisbury", "party": "Conservative", "termStart": 1885, "termEnd": 1886, "context": "The last Prime Minister to lead from the House of Lords, he presided over the height of the British Empire.", "contextFr": "Dernier Premier ministre à diriger depuis la Chambre des lords, il a présidé à l'apogée de l'Empire britannique.", "contextJa": "貴族院から国を導いた最後の首相であり、大英帝国の最盛期を統治しました。", "contextEs": "El último Primer Ministro en liderar desde la Cámara de los Lores, presidió el apogeo del Imperio Británico.", "contextZh": "最后一位在上议院领导政府的首相，他主持了大英帝国的鼎盛时期。", "contextAr": "آخر رئيس وزراء يقود من مجلس اللوردات، ترأس ذروة الإمبراطورية البريطانية.", "contextHi": "हाउस ऑफ लॉर्ड्स से नेतृत्व करने वाले अंतिम प्रधानमंत्री, उन्होंने ब्रिटिश साम्राज्य के चरम की अध्यक्षता की।", "imageUrl": "https://i.ibb.co/nqzj92F3/Robert-Gascoyne-Cecil-3rd-Marquess-of-Salisbury.webp", "coatOfArmsUrl": "https://i.ibb.co/gFL96Vzk/Tory.png" },
  { "id": 15, "name": "H. H. Asquith", "party": "Liberal", "termStart": 1908, "termEnd": 1916, "context": "His government introduced major social welfare reforms but led Britain into World War I.", "contextFr": "Son gouvernement a introduit d'importantes réformes de protection sociale mais a conduit la Grande-Bretagne dans la Première Guerre mondiale.", "contextJa": "彼の政府は主要な社会福祉改革を導入しましたが、英国を第一次世界大戦へと導きました。", "contextEs": "Su gobierno introdujo importantes reformas de bienestar social, pero llevó a Gran Bretaña a la Primera Guerra Mundial.", "contextZh": "他的政府引入了重大的社会福利改革，但带领英国卷入了第一次世界大战。", "contextAr": "أدخلت حكومته إصلاحات كبيرة في الرعاية الاجتماعية لكنها قادت بريطانيا إلى الحرب العالمية الأولى.", "contextHi": "उनकी सरकार ने प्रमुख सामाजिक कल्याण सुधार पेश किए लेकिन ब्रिटेन को प्रथम विश्व युद्ध में ले गई।", "imageUrl": "https://i.ibb.co/ymV6n7m0/783px-Herbert-Henry-Asquith.webp", "coatOfArmsUrl": "https://i.ibb.co/1YPWCxVK/LibDems.png" },
  { "id": 16, "name": "David Lloyd George", "party": "Liberal", "termStart": 1916, "termEnd": 1922, "context": "The 'Welsh Wizard' who led Britain to victory in World War I and was a key figure at the Paris Peace Conference.", "contextFr": "Le « Magicien gallois » qui a mené la Grande-Bretagne à la victoire lors de la Première Guerre mondiale et a été une figure clé de la Conférence de paix de Paris.", "contextJa": "第一次世界大戦で英国を勝利に導き、パリ講和会議で重要な役割を果たした「ウェールズの魔法使い」。", "contextEs": "El 'Mago Galés' que llevó a Gran Bretaña a la victoria en la Primera Guerra Mundial y fue una figura clave en la Conferencia de Paz de París.", "contextZh": "带领英国在第一次世界大战中取得胜利的“威尔士巫师”，也是巴黎和会的关键人物。", "contextAr": "'الساحر الويلزي' الذي قاد بريطانيا إلى النصر في الحرب العالمية الأولى وكان شخصية رئيسية في مؤتمر باريس للسلام.", "contextHi": "'वेल्श विजार्ड' जिन्होंने प्रथम विश्व युद्ध में ब्रिटेन को जीत दिलाई और पेरिस शांति सम्मेलन में एक प्रमुख व्यक्ति थे।", "imageUrl": "https://i.ibb.co/rfZrhn3Y/David-Lloyd-George-786x1024.webp", "coatOfArmsUrl": "https://i.ibb.co/1YPWCxVK/LibDems.png" },
  { "id": 17, "name": "Neville Chamberlain", "party": "Conservative", "termStart": 1937, "termEnd": 1940, "context": "Best known for his policy of appeasement towards Nazi Germany, which ended with the invasion of Poland.", "contextFr": "Surtout connu pour sa politique d'apaisement envers l'Allemagne nazie, qui s'est terminée par l'invasion de la Pologne.", "contextJa": "ナチス・ドイツに対する宥和政策で最もよく知られており、それはポーランド侵攻で終わりました。", "contextEs": "Mejor conocido por su política de apaciguamiento hacia la Alemania nazi, que terminó con la invasión de Polonia.", "contextZh": "以对纳粹德国的绥靖政策而闻名，该政策以德国入侵波兰而告终。", "contextAr": "اشتهر بسياسة الاسترضاء تجاه ألمانيا النازية، والتي انتهت بغزو بولندا.", "contextHi": "नाजी जर्मनी के प्रति अपनी तुष्टीकरण की नीति के लिए सबसे ज्यादा जाने जाते हैं, जो पोलैंड पर आक्रमण के साथ समाप्त हुई।", "imageUrl": "https://i.ibb.co/VY1W4t2P/Neville-Chamberlain.webp", "coatOfArmsUrl": "https://i.ibb.co/gFL96Vzk/Tory.png" },
  { "id": 18, "name": "Winston Churchill", "party": "Conservative", "termStart": 1940, "termEnd": 1945, "context": "Inspired Britain to victory in World War II with his powerful speeches and refusal to surrender.", "contextFr": "A inspiré la Grande-Bretagne à la victoire lors de la Seconde Guerre mondiale avec ses discours puissants et son refus de se rendre.", "contextJa": "力強い演説と降伏の拒否により、第二次世界大戦で英国を勝利に導きました。", "contextEs": "Inspiró a Gran Bretaña a la victoria en la Segunda Guerra Mundial con sus poderosos discursos y su negativa a rendirse.", "contextZh": "凭借强有力的演讲和拒绝投降的决心，激励英国在第二次世界大战中取得胜利。", "contextAr": "ألهم بريطانيا لتحقيق النصر في الحرب العالمية الثانية بخطاباته القوية ورفضه الاستسلام.", "contextHi": "अपने शक्तिशाली भाषणों और आत्मसमर्पण करने से इनकार करने के साथ द्वितीय विश्व युद्ध में जीत के लिए ब्रिटेन को प्रेरित किया।", "imageUrl": "https://i.ibb.co/PvLsmC12/Sir-Winston-Churchill-19086236948.webp", "coatOfArmsUrl": "https://i.ibb.co/gFL96Vzk/Tory.png" },
  { "id": 19, "name": "Clement Attlee", "party": "Labour", "termStart": 1945, "termEnd": 1951, "context": "His government established the National Health Service (NHS) and the modern welfare state after World War II.", "contextFr": "Son gouvernement a créé le National Health Service (NHS) et l'État-providence moderne après la Seconde Guerre mondiale.", "contextJa": "彼の政府は、第二次世界大戦後に国民保健サービス（NHS）と現代の福祉国家を設立しました。", "contextEs": "Su gobierno estableció el Servicio Nacional de Salud (NHS) y el estado de bienestar moderno después de la Segunda Guerra Mundial.", "contextZh": "他的政府在二战后建立了国民保健署（NHS）和现代福利国家。", "contextAr": "أسست حكومته هيئة الخدمات الصحية الوطنية (NHS) ودولة الرفاهية الحديثة بعد الحرب العالمية الثانية.", "contextHi": "उनकी सरकार ने द्वितीय विश्व युद्ध के बाद राष्ट्रीय स्वास्थ्य सेवा (NHS) और आधुनिक कल्याणकारी राज्य की स्थापना की।", "imageUrl": "https://i.ibb.co/NgJn1pJK/Clement-Attlee.webp", "coatOfArmsUrl": "https://i.ibb.co/ymxD90xn/Labour.png" },
  { "id": 20, "name": "Harold Macmillan", "party": "Conservative", "termStart": 1957, "termEnd": 1963, "context": "Known as 'Supermac', he told Britons they had 'never had it so good' during a period of affluence.", "contextFr": "Connu sous le nom de « Supermac », il a dit aux Britanniques qu'ils n'avaient « jamais été aussi bien lotis » pendant une période d'abondance.", "contextJa": "「スーパーマック」として知られ、豊かな時代に英国民に「かつてないほど良い時代だ」と語りました。", "contextEs": "Conocido como 'Supermac', dijo a los británicos que 'nunca lo habían tenido tan bien' durante un período de afluencia.", "contextZh": "被称为“超级麦克”，他在富裕时期告诉英国人他们“从未有过如此美好的日子”。", "contextAr": "يُعرف باسم 'سوبرماك'، أخبر البريطانيين أنهم 'لم يعيشوا وقتًا أفضل من هذا' خلال فترة من الرخاء.", "contextHi": "'सुपरमैक' के रूप में जाने जाने वाले, उन्होंने संपन्नता की अवधि के दौरान ब्रितानियों से कहा कि 'उनके पास इससे बेहतर कभी नहीं था'।", "imageUrl": "https://i.ibb.co/Fk8nktYW/Harold-Mac-Millan-1st-Earl-of-Stockton.webp", "coatOfArmsUrl": "https://i.ibb.co/gFL96Vzk/Tory.png" },
  { "id": 21, "name": "Harold Wilson", "party": "Labour", "termStart": 1964, "termEnd": 1970, "context": "Led during the 'Swinging Sixties', a time of social liberalisation, and created the Open University.", "contextFr": "A dirigé pendant les « Swinging Sixties », une époque de libéralisation sociale, et a créé l'Open University.", "contextJa": "社会の自由化の時代である「スウィンギング・シックスティーズ」を牽引し、オープン大学を創設しました。", "contextEs": "Lideró durante los 'Swinging Sixties', una época de liberalización social, y creó la Open University.", "contextZh": "在“摇摆的六十年代”（社会自由化时期）领导国家，并创建了开放大学。", "contextAr": "قاد خلال 'الستينيات المتأرجحة'، وهي فترة من التحرر الاجتماعي، وأنشأ الجامعة المفتوحة.", "contextHi": "'स्विंगिंग सिक्सटीज़', सामाजिक उदारीकरण के समय के दौरान नेतृत्व किया, और ओपन यूनिवर्सिटी की स्थापना की।", "imageUrl": "https://i.ibb.co/v6mFHSjV/Harold-Wilson2.webp", "coatOfArmsUrl": "https://i.ibb.co/ymxD90xn/Labour.png" },
  { "id": 22, "name": "Edward Heath", "party": "Conservative", "termStart": 1970, "termEnd": 1974, "context": "Took the United Kingdom into the European Economic Community (EEC) in 1973.", "contextFr": "A fait entrer le Royaume-Uni dans la Communauté économique européenne (CEE) en 1973.", "contextJa": "1973年に英国を欧州経済共同体（EEC）に加盟させました。", "contextEs": "Llevó al Reino Unido a la Comunidad Económica Europea (CEE) en 1973.", "contextZh": "在1973年带领英国加入欧洲经济共同体（EEC）。", "contextAr": "أدخل المملكة المتحدة إلى المجموعة الاقتصادية الأوروبية (EEC) في عام 1973.", "contextHi": "1973 में यूके को यूरोपीय आर्थिक समुदाय (EEC) में ले गए।", "imageUrl": "https://i.ibb.co/3ytQKRb8/Sir-Edward-Heath.webp", "coatOfArmsUrl": "https://i.ibb.co/gFL96Vzk/Tory.png" },
  { "id": 23, "name": "James Callaghan", "party": "Labour", "termStart": 1976, "termEnd": 1979, "context": "His term ended with the 'Winter of Discontent', a period of widespread public sector strikes.", "contextFr": "Son mandat s'est terminé par l'« Hiver du mécontentement », une période de grèves généralisées dans le secteur public.", "contextJa": "彼の任期は、広範な公共部門のストライキの期間である「不満の冬」で終わりました。", "contextEs": "Su mandato terminó con el 'Invierno del Descontento', un período de huelgas generalizadas en el sector público.", "contextZh": "他的任期以“不满的冬天”结束，这是一个公共部门广泛罢工的时期。", "contextAr": "انتهت فترة ولايته بـ 'شتاء السخط'، وهي فترة من الإضرابات الواسعة النطاق في القطاع العام.", "contextHi": "उनका कार्यकाल 'असंतोष की सर्दी' के साथ समाप्त हुआ, जो व्यापक सार्वजनिक क्षेत्र की हड़तालों की अवधि थी।", "imageUrl": "https://i.ibb.co/MkQwtxDb/James-Callaghan-1975-754x1024.webp", "coatOfArmsUrl": "https://i.ibb.co/ymxD90xn/Labour.png" },
  { "id": 24, "name": "Margaret Thatcher", "party": "Conservative", "termStart": 1979, "termEnd": 1990, "context": "The 'Iron Lady' was Britain's first female Prime Minister, known for privatisation and confronting trade unions.", "contextFr": "La « Dame de fer » a été la première femme Premier ministre de Grande-Bretagne, connue pour ses privatisations et sa confrontation avec les syndicats.", "contextJa": "「鉄の女」は英国初の女性首相であり、民営化と労働組合との対決で知られています。", "contextEs": "La 'Dama de Hierro' fue la primera mujer Primer Ministro de Gran Bretaña, conocida por la privatización y el enfrentamiento con los sindicatos.", "contextZh": "“铁娘子”是英国第一位女首相，以私有化和对抗工会而闻名。", "contextAr": "'المرأة الحديدية' كانت أول رئيسة وزراء لبريطانيا، عُرفت بالخصخصة ومواجهة النقابات العمالية.", "contextHi": "'आयरन लेडी' ब्रिटेन की पहली महिला प्रधानमंत्री थीं, जो निजीकरण और ट्रेड यूनियनों से मुकाबला करने के लिए जानी जाती थीं।", "imageUrl": "https://i.ibb.co/KjwF6Mrq/F-Margaret-Thatcher-stock-portrait-cropped-736x1024.webp", "coatOfArmsUrl": "https://i.ibb.co/gFL96Vzk/Tory.png" },
  { "id": 25, "name": "John Major", "party": "Conservative", "termStart": 1990, "termEnd": 1997, "context": "Oversaw British involvement in the Gulf War and initiated the Northern Ireland peace process.", "contextFr": "A supervisé l'implication britannique dans la guerre du Golfe et a initié le processus de paix en Irlande du Nord.", "contextJa": "湾岸戦争への英国の関与を監督し、北アイルランド和平プロセスを開始しました。", "contextEs": "Supervisó la participación británica en la Guerra del Golfo e inició el proceso de paz de Irlanda del Norte.", "contextZh": "监督英国参与海湾战争，并启动了北爱尔兰和平进程。", "contextAr": "أشرف على التدخل البريطاني في حرب الخليج وبدأ عملية السلام في أيرلندا الشمالية.", "contextHi": "खाड़ी युद्ध में ब्रिटिश भागीदारी की देखरेख की और उत्तरी आयरलैंड शांति प्रक्रिया शुरू की।", "imageUrl": "https://i.ibb.co/HfmYsFGN/John-Major-B4-M4-CE.webp", "coatOfArmsUrl": "https://i.ibb.co/gFL96Vzk/Tory.png" },
  { "id": 26, "name": "Tony Blair", "party": "Labour", "termStart": 1997, "termEnd": 2007, "context": "Led 'New Labour' to a landslide victory, oversaw the Good Friday Agreement, and supported the 2003 invasion of Iraq.", "contextFr": "A mené le « New Labour » à une victoire écrasante, a supervisé l'Accord du Vendredi saint et a soutenu l'invasion de l'Irak en 2003.", "contextJa": "「ニュー・レイバー」を地滑り的勝利に導き、ベルファスト合意を監督し、2003年のイラク侵攻を支持しました。", "contextEs": "Llevó al 'Nuevo Laborismo' a una victoria aplastante, supervisó el Acuerdo del Viernes Santo y apoyó la invasión de Irak en 2003.", "contextZh": "带领“新工党”取得压倒性胜利，监督了《耶稣受难日协议》，并支持2003年入侵伊拉克。", "contextAr": "قاد 'حزب العمال الجديد' إلى فوز ساحق، وأشرف على اتفاقية الجمعة العظيمة، ودعم غزو العراق عام 2003.", "contextHi": "'न्यू लेबर' को भारी जीत दिलाई, गुड फ्राइडे समझौते की देखरेख की, और 2003 के इराक आक्रमण का समर्थन किया।", "imageUrl": "https://i.ibb.co/RLdqJF0/Tony-Blair2010.webp", "coatOfArmsUrl": "https://i.ibb.co/ymxD90xn/Labour.png" },
  { "id": 27, "name": "Gordon Brown", "party": "Labour", "termStart": 2007, "termEnd": 2010, "context": "His premiership was dominated by the 2008 global financial crisis.", "contextFr": "Son mandat a été dominé par la crise financière mondiale de 2008.", "contextJa": "彼の任期は2008年の世界金融危機に支配されました。", "contextEs": "Su mandato estuvo dominado por la crisis financiera mundial de 2008.", "contextZh": "他的任期被2008年全球金融危机所主导。", "contextAr": "هيمنت الأزمة المالية العالمية لعام 2008 على فترة رئاسته للوزراء.", "contextHi": "उनका कार्यकाल 2008 के वैश्विक वित्तीय संकट के प्रभुत्व में था।", "imageUrl": "https://i.ibb.co/k2b3YSXR/Gordon-Brown2008.webp", "coatOfArmsUrl": "https://i.ibb.co/ymxD90xn/Labour.png" },
  { "id": 28, "name": "David Cameron", "party": "Conservative", "termStart": 2010, "termEnd": 2016, "context": "Formed the first coalition government since WWII and held the Scottish independence and Brexit referendums.", "contextFr": "A formé le premier gouvernement de coalition depuis la Seconde Guerre mondiale et a organisé les référendums sur l'indépendance de l'Écosse et le Brexit.", "contextJa": "第二次世界大戦後初の連立政権を樹立し、スコットランド独立とブレグジットの国民投票を実施しました。", "contextEs": "Formó el primer gobierno de coalición desde la Segunda Guerra Mundial y celebró los referéndums de independencia de Escocia y del Brexit.", "contextZh": "组建了自二战以来的首个联合政府，并举行了苏格兰独立和英国脱欧公投。", "contextAr": "شكل أول حكومة ائتلافية منذ الحرب العالمية الثانية وأجرى استفتاءات استقلال اسكتلندا وخروج بريطانيا من الاتحاد الأوروبي.", "contextHi": "द्वितीय विश्व युद्ध के बाद पहली गठबंधन सरकार बनाई और स्कॉटिश स्वतंत्रता और ब्रेक्सिट जनमत संग्रह आयोजित किए।", "imageUrl": "https://i.ibb.co/v69gVhwb/Prime-Minister-David-Cameronofficialphotograph8947770804cropped.webp", "coatOfArmsUrl": "https://i.ibb.co/gFL96Vzk/Tory.png" },
  { "id": 29, "name": "Theresa May", "party": "Conservative", "termStart": 2016, "termEnd": 2019, "context": "Became Prime Minister after the Brexit vote and spent her premiership negotiating a withdrawal agreement.", "contextFr": "Devenue Premier ministre après le vote sur le Brexit et a passé son mandat à négocier un accord de retrait.", "contextJa": "ブレグジットの投票後に首相となり、任期を離脱協定の交渉に費やしました。", "contextEs": "Se convirtió en Primera Ministra después de la votación del Brexit y pasó su mandato negociando un acuerdo de retirada.", "contextZh": "在脱欧公投后成为首相，并在其任期内致力于谈判脱欧协议。", "contextAr": "أصبحت رئيسة للوزراء بعد تصويت خروج بريطانيا من الاتحاد الأوروبي وقضت فترة ولايتها في التفاوض على اتفاقية الانسحاب.", "contextHi": "ब्रेक्सिट वोट के बाद प्रधानमंत्री बनीं और अपना कार्यकाल वापसी समझौते पर बातचीत करने में बिताया।", "imageUrl": "https://i.ibb.co/XkdhrKpy/Theresa-May-2016-cropped.webp", "coatOfArmsUrl": "https://i.ibb.co/gFL96Vzk/Tory.png" },
  { "id": 30, "name": "Boris Johnson", "party": "Conservative", "termStart": 2019, "termEnd": 2022, "context": "Won a large majority on a promise to 'Get Brexit Done' and led the country through the COVID-19 pandemic.", "contextFr": "A remporté une large majorité sur la promesse de « réaliser le Brexit » et a dirigé le pays pendant la pandémie de COVID-19.", "contextJa": "「ブレグジットを成し遂げる」という約束で過半数を獲得し、COVID-19パンデミックの中で国を導きました。", "contextEs": "Ganó una amplia mayoría con la promesa de 'Get Brexit Done' y lideró el país durante la pandemia de COVID-19.", "contextZh": "以“完成脱欧”的承诺赢得绝对多数，并带领国家度过了COVID-19大流行。", "contextAr": "فاز بأغلبية كبيرة بناءً على وعد بـ 'إنجاز خروج بريطانيا من الاتحاد الأوروبي' وقاد البلاد خلال جائحة كوفيد-19.", "contextHi": "'गेट ब्रेक्सिट डन' के वादे पर भारी बहुमत जीता और COVID-19 महामारी के दौरान देश का नेतृत्व किया।", "imageUrl": "https://i.ibb.co/cSDpWHrk/Boris-Johnsonofficialportraitcropped-728x1024.webp", "coatOfArmsUrl": "https://i.ibb.co/gFL96Vzk/Tory.png" },
  { "id": 31, "name": "Liz Truss", "party": "Conservative", "termStart": 2022, "termEnd": 2022, "context": "Served the shortest term of any UK Prime Minister, resigning after 49 days following economic turmoil.", "contextFr": "A effectué le mandat le plus court de tous les Premiers ministres britanniques, démissionnant après 49 jours suite à des troubles économiques.", "contextJa": "英国の首相として最短の任期を務め、経済的混乱の末に49日で辞任しました。", "contextEs": "Sirvió el mandato más corto de cualquier Primer Ministro del Reino Unido, renunciando después de 49 días tras la agitación económica.", "contextZh": "是英国历史上任期最短的首相，在经济动荡后仅49天便辞职。", "contextAr": "قضت أقصر فترة ولاية لأي رئيس وزراء بريطاني، حيث استقالت بعد 49 يومًا في أعقاب اضطرابات اقتصادية.", "contextHi": "आर्थिक उथल-पुथल के बाद 49 दिनों के बाद इस्तीफा देकर, यूके के किसी भी प्रधानमंत्री का सबसे छोटा कार्यकाल पूरा किया।", "imageUrl": "https://i.ibb.co/nsJy7sGr/Officialportraitof-Liz-Trusscropped.webp", "coatOfArmsUrl": "https://i.ibb.co/gFL96Vzk/Tory.png" },
  { "id": 32, "name": "Rishi Sunak", "party": "Conservative", "termStart": 2022, "termEnd": 2024, "context": "Became Prime Minister during a period of economic instability, focusing on restoring fiscal credibility.", "contextFr": "Devenu Premier ministre pendant une période d'instabilité économique, se concentrant sur le rétablissement de la crédibilité budgétaire.", "contextJa": "経済的不安定な時期に首相となり、財政の信頼性回復に注力しました。", "contextEs": "Se convirtió en Primer Ministro durante un período de inestabilidad económica, centrándose en restaurar la credibilidad fiscal.", "contextZh": "在经济不稳定时期成为首相，致力于恢复财政信誉。", "contextAr": "أصبح رئيسًا للوزراء خلال فترة من عدم الاستقرار الاقتصادي، مع التركيز على استعادة المصداقية المالية.", "contextHi": "आर्थिक अस्थिरता की अवधि के दौरान प्रधानमंत्री बने, राजकोषीय विश्वसनीयता बहाल करने पर ध्यान केंद्रित किया।", "imageUrl": "https://i.ibb.co/FL1tBcSd/Portrait-of-Prime-Minister-Rishi-Sunak-cropped.webp", "coatOfArmsUrl": "https://i.ibb.co/gFL96Vzk/Tory.png" },
  { "id": 33, "name": "Keir Starmer", "party": "Labour", "termStart": 2024, "termEnd": 2026, "context": "Led the Labour Party to a landslide victory in the 2024 general election, ending 14 years of Conservative rule.", "contextFr": "A mené le Parti travailliste à une victoire écrasante lors des élections générales de 2024, mettant fin à 14 ans de régime conservateur.", "contextJa": "2024年の総選挙で労働党を地滑り的勝利に導き、14年間の保守党政権に終止符を打ちました。", "contextEs": "Llevó al Partido Laborista a una victoria aplastante en las elecciones generales de 2024, poniendo fin a 14 años de gobierno conservador.", "contextZh": "带领工党在2024年大选中取得压倒性胜利，结束了保守党长达14年的执政。", "contextAr": "قاد حزب العمال إلى فوز ساحق في الانتخابات العامة لعام 2024، منهياً 14 عاماً من حكم المحافظين.", "contextHi": "2024 के आम चुनाव में लेबर पार्टी को भारी जीत दिलाई, जिससे 14 साल के कंजर्वेटिव शासन का अंत हुआ।", "imageUrl": "https://i.ibb.co/01sLFfJ/Keir-Starmer-Alamy-T8-RBGG.webp", "coatOfArmsUrl": "https://i.ibb.co/ymxD90xn/Labour.png" },
  {
    "id": 34,
    "name": "Andy Burnham",
    "party": "Labour",
    "termStart": 2026,
    "termEnd": null,
    "context": "The 'King of the North', who served as Mayor of Greater Manchester before entering Downing Street, championing regional devolution, social care reform, and public transport integration.",
    "contextFr": "Le « Roi du Nord », qui a été maire du Grand Manchester avant d'entrer à Downing Street, défendant la décentralisation régionale, la réforme de l'aide sociale et l'intégration des transports publics.",
    "contextJa": "「北部の王」として知られ、ダウニング街に入る前にグレーター・マンチェスター市長を務め、地方分権、社会的ケアの改革、および公共交通機関の統合を推進しました。",
    "contextEs": "El 'Rey del Norte', quien se desempeñó como alcalde del Gran Mánchester antes de ingresar a Downing Street, defendiendo la devolución regional, la reforma del cuidado social y la integración del transporte público.",
    "contextZh": "被称为“北方之王”，在入主唐宁街之前曾担任大曼彻斯特市长，倡导地方权力下放、社会福利改革以及公共交通一体化。",
    "contextAr": "يُلقب بـ 'ملك الشمال'، شغل منصب عمدة مانشستر الكبرى قبل دخوله داونينغ ستريت، حيث دافع عن نقل السلطات الإقليمية، وإصلاح الرعاية الاجتماعية، وتكامل النقل العام.",
    "contextHi": "'किंग ऑफ द नॉर्थ' के रूप में जाने जाने वाले, जिन्होंने डाउनिंग स्ट्रीट में प्रवेश करने से पहले ग्रेटर मैनचेस्टर के मेयर के रूप में कार्य किया, क्षेत्रीय हस्तांतरण, समाज कल्याण सुधार और सार्वजनिक परिवहन एकीकरण का समर्थन किया।",
    "imageUrl": andyBurnhamPortrait,
    "coatOfArmsUrl": "https://i.ibb.co/ymxD90xn/Labour.png"
  }
];


export const getGamePrimeMinisters = (sourcePMs: PrimeMinister[]): PrimeMinister[] => {
  const shuffled = [...sourcePMs].sort(() => 0.5 - Math.random());
  return shuffled.slice(0, ROUNDS_PER_GAME);
};

export const getSuccessorPrimeMinisters = (sourcePMs: PrimeMinister[]): PrimeMinister[] => {
  // Exclude the last PM as they have no successor in the list
  const eligiblePMs = sourcePMs.slice(0, -1);
  const shuffled = [...eligiblePMs].sort(() => 0.5 - Math.random());
  return shuffled.slice(0, ROUNDS_PER_GAME);
};
